name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ["erlang:27", "erlang:28"]

    container:
      image: ${{ matrix.otp }}

    steps:
    - uses: actions/checkout@v4
    - name: Install latest g++
      run: |
        apt-get update -y
        GCC_VSN=$(apt-cache search '^g\+\+-[0-9]+$' | grep -oP '\d+(?=\s)' | sort -n | tail -1)
        apt-get install -y g++-${GCC_VSN}
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VSN} 100
        g++ --version
        git config --global user.name "Test User"
        git config --global user.email "test@gmail.com"
    - name: Install libgit2
      run: |
        apt-get update -y && apt-get install -y libgit2-dev
    - name: Compile
      run:  make
    - name: Dialyze
      run:  make check
    - name: Run tests
      run:  make test
