name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ["erlang:27"]

    container:
      image: ${{ matrix.otp }}

    steps:
    - uses: actions/checkout@v2
    - name: Install latest g++
      run: |
        ls -l /usr/bin/g++*
        sudo apt install gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
        sudo update-alternatives --set gcc /usr/bin/gcc-10
        g++ --version
        git config --global user.name "Test User"
        git config --global user.email "test@gmail.com"
    - name: Install libgit2
      run: |
        apt-get update -y && apt-get install -y libgit2-dev
    - name: Compile
      run:  make
    - name: Dialyze
      run:  make check
    - name: Run tests
      run:  make test
